name: Auto Assign PR to Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Assign the PR to the author
    - name: Assign PR to Author
      uses: actions/github-script@v6
      with:
        script: |
          const author = context.payload.pull_request.user.login;
          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: [author]
          });
