name: Auto Assign PR to Author

on:
  pull_request:
    types: [opened]

permissions:
  contents: read  # Minimum required permission to check out the code
  pull-requests: write  # Permission to modify PRs, like assigning it to the author
  issues: write  # Permission to assign issues (PRs are a type of issue)

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Assign the PR to the author
      - name: Assign PR to Author
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Provide the GITHUB_TOKEN here
          script: |
            const author = context.payload.pull_request.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [author]
            });
      - name: Debug secrets
        run: echo "GITHUB_TOKEN is available"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
