name: Demo to create automatic PR 

on:
    push:
        branches:
            - main

jobs: 
    updateAuthor:
        runs-on: ubuntu-latest
        steps:
            - name: checking out code 
              uses: actions/checkout@v2
            
            - name: extract git commit data
              uses: rlespinasse/git-commit-data-action@v1.x

            - name: Set Commit Information
              id: set-vars
              run: |
                   echo "GIT_COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
                   echo "GIT_COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                branch: auto-pr-branch
                base: main
                title: "Demo for Auto PR"
                body: |
                    This is to show automatic PR creation
                token: ${{ secrets.GITHUB_TOKEN }}
                delete-branch: true