name: Auto Assign Author

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Auto assign author
        uses: toshimaru/auto-author-assign@v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
